spring:
  application:
    name: sisyphus
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:pianoshop-db
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    path: /docs
jwt:
  key-store: inholland.p12
  key-store-password: geheim
  key-alias: inholland